In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error

### DB SOURCE - https://www.kaggle.com/anthonypino/melbourne-housing-market/

In [3]:
df = pd.read_csv(r"C:\Users\user\Desktop\machine learning\house_pricing\Melbourne_housing_FULL.csv")

## previously removed some columns wich we dont need here, you can check full table ot the link(we dont need to overweight the model with excess data)

In [20]:
df.tail(7)

,Suburb,Rooms,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea
34850,Wollert,3,h,NaN,25.5,3.0,2.0,2.0,268.0,135.0,2016.0,Whittlesea City Council
34851,Yarraville,3,h,1101000.0,6.3,3.0,1.0,NaN,288.0,NaN,NaN,Maribyrnong City Council
34852,Yarraville,4,h,1480000.0,6.3,4.0,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council
34853,Yarraville,2,h,888000.0,6.3,2.0,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council
34854,Yarraville,2,t,705000.0,6.3,2.0,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council
34855,Yarraville,3,h,1140000.0,6.3,NaN,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council
34856,Yarraville,2,h,1020000.0,6.3,2.0,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council

# cleaning the db from NaNs

In [22]:
df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)

In [40]:
df.head(10) #check

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Suburb_Abbotsford,...,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Type_h,Type_t,Type_u
2,2,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,1,...,0,0,0,0,0,1,0,1,0,0
4,3,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,1,...,0,0,0,0,0,1,0,1,0,0
6,4,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,1,...,0,0,0,0,0,1,0,1,0,0
11,3,1876000.0,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,1,...,0,0,0,0,0,1,0,1,0,0
14,2,1636000.0,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,1,...,0,0,0,0,0,1,0,1,0,0
18,2,1097000.0,2.5,3.0,1.0,2.0,220.0,75.0,1900.0,1,...,0,0,0,0,0,1,0,1,0,0
24,3,1350000.0,2.5,3.0,2.0,2.0,214.0,190.0,2005.0,1,...,0,0,0,0,0,1,0,1,0,0
25,2,750000.0,2.5,2.0,2.0,1.0,0.0,94.0,2009.0,1,...,0,0,0,0,0,1,0,0,0,1
30,2,1310000.0,2.5,2.0,1.0,2.0,238.0,97.0,1890.0,1,...,0,0,0,0,0,1,0,1,0,0
32,3,1200000.0,2.5,3.0,2.0,1.0,113.0,110.0,1880.0,1,...,0,0,0,0,0,1,0,1,0,0

In [27]:
df = pd.get_dummies(df,columns = ['Suburb','CouncilArea','Type'])

In [29]:
df.head(5)

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Suburb_Abbotsford,...,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Type_h,Type_t,Type_u
2,2,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,1,...,0,0,0,0,0,1,0,1,0,0
4,3,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,1,...,0,0,0,0,0,1,0,1,0,0
6,4,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,1,...,0,0,0,0,0,1,0,1,0,0
11,3,1876000.0,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,1,...,0,0,0,0,0,1,0,1,0,0
14,2,1636000.0,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,1,...,0,0,0,0,0,1,0,1,0,0

# taking independant and dependant columns for X & Y vectors

In [30]:
X = df.drop('Price', axis = 1)

## price will be prediction

In [31]:
y = df['Price']

In [32]:
y

2        1035000.0
4        1465000.0
6        1600000.0
11       1876000.0
14       1636000.0
           ...
34847     500000.0
34849     570000.0
34853     888000.0
34854     705000.0
34856    1020000.0
Name: Price, Length: 8895, dtype: float64

In [39]:
X ##check

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Suburb_Abbotsford,Suburb_Aberfeldie,...,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Type_h,Type_t,Type_u
2,2,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,1,0,...,0,0,0,0,0,1,0,1,0,0
4,3,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,1,0,...,0,0,0,0,0,1,0,1,0,0
6,4,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,1,0,...,0,0,0,0,0,1,0,1,0,0
11,3,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,1,0,...,0,0,0,0,0,1,0,1,0,0
14,2,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,1,0,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,3,25.5,3.0,2.0,2.0,383.0,118.0,2016.0,0,0,...,0,0,0,1,0,0,0,1,0,0
34849,3,25.5,3.0,2.0,2.0,404.0,158.0,2012.0,0,0,...,0,0,0,1,0,0,0,1,0,0
34853,2,6.3,2.0,2.0,1.0,98.0,104.0,2018.0,0,0,...,0,0,0,0,0,0,0,1,0,0
34854,2,6.3,2.0,1.0,2.0,220.0,120.0,2000.0,0,0,...,0,0,0,0,0,0,0,0,1,0
34856,2,6.3,2.0,1.0,0.0,250.0,103.0,1930.0,0,0,...,0,0,0,0,0,0,0,1,0,0

## SPLITTING THE DB (and shuffle - !!important) 70-30%

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, shuffle=True)

In [38]:
X_train ##check

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Suburb_Abbotsford,Suburb_Aberfeldie,...,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Type_h,Type_t,Type_u
25620,3,27.0,3.0,2.0,3.0,564.0,150.0,1950.0,0,0,...,0,0,0,0,0,0,0,1,0,0
17597,5,12.3,5.0,2.0,3.0,548.0,157.0,1920.0,0,0,...,0,0,0,0,0,0,0,1,0,0
4589,3,9.2,3.0,1.0,3.0,650.0,136.0,1930.0,0,0,...,0,0,0,0,0,0,0,1,0,0
24310,3,17.4,3.0,1.0,1.0,553.0,89.0,1970.0,0,0,...,0,0,0,0,0,0,0,1,0,0
3922,2,7.7,2.0,1.0,1.0,0.0,75.0,1975.0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9135,3,2.1,3.0,2.0,0.0,171.0,126.0,1890.0,0,0,...,1,0,0,0,0,0,0,1,0,0
33889,4,6.8,4.0,3.0,2.0,509.0,127.0,1990.0,0,0,...,0,0,0,0,0,0,0,1,0,0
7162,2,11.2,2.0,2.0,1.0,268.0,104.0,1950.0,0,0,...,0,0,0,0,0,0,0,1,0,0
15149,2,6.2,2.0,1.0,0.0,251.0,110.0,1980.0,0,0,...,0,0,0,0,0,0,0,1,0,0
20991,3,10.5,3.0,1.0,3.0,287.0,110.0,1910.0,0,0,...,0,0,0,0,0,0,0,1,0,0

### selecting alorithm - gradient boosting regressor(we need regression not classification in this model)

In [42]:
model = ensemble.GradientBoostingRegressor(n_estimators=150,learning_rate=0.1,max_depth=30,min_samples_split=4,
                                          min_samples_leaf=6,max_features=0.6,loss='huber')

## train the model

In [44]:
model.fit(X_train,y_train)

GradientBoostingRegressor(loss='huber', max_depth=30, max_features=0.6,
                          min_samples_leaf=6, min_samples_split=4,
                          n_estimators=150)

# evaluation

In [45]:
mae_train = mean_absolute_error(y_train, model.predict(X_train))

In [48]:
print("%.2f"%mae_train)

27384.29

In [49]:
mae_test = mean_absolute_error(y_test, model.predict(X_test))

In [50]:
print("%.2f"%mae_test)

167524.73